import {useState} from 'react';
import {useMutation} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {timeLabel,type AttendanceDto,type StatusDto} from '../../../../packages/shared/src/index';
import {api,json,queryClient,useStatuses} from '../api';
import {Avatar,ErrorBox,Loading,StatusBadge,StatusSelector,Empty} from './ui';
export function AgentStatusCard({row,date,editable=true}:{row:AttendanceDto;date:string;editable?:boolean}){const [optimistic,setOptimistic]=useState<string|null>(null);const statuses=useStatuses();const mutation=useMutation({mutationFn:(status:string)=>api('/attendance/'+row.agentId,json('PATCH',{status,date})),onMutate:status=>setOptimistic(status),onError:()=>setOptimistic(null),onSuccess:async()=>{await queryClient.invalidateQueries({queryKey:['attendance']});await queryClient.invalidateQueries({queryKey:['dashboard']});setOptimistic(null);}});if(!statuses.data)return <Loading/>;return <article className="agent-card"><div className="agent-identity"><Avatar name={row.agent.fullName} url={row.agent.avatarUrl}/><div><h3>{row.agent.fullName}</h3><p className="muted">{row.agent.jobTitle}</p></div></div><div className="agent-status">{editable?<StatusSelector name={row.agent.fullName} statuses={statuses.data} statusKey={optimistic??row.currentStatus} disabled={mutation.isPending} onSelect={s=>mutation.mutate(s)}/>:<StatusBadge statuses={statuses.data} statusKey={row.currentStatus}/>}<small className="muted">{mutation.isPending?'Saving…':row.lastUpdatedAt?'Updated '+timeLabel(row.lastUpdatedAt):'Awaiting update'}</small></div>{mutation.error&&<ErrorBox error={mutation.error} retry={()=>mutation.mutate(mutation.variables!)}/>}</article>;}
export function AttendanceTable({rows,date,editable=false,history=false}:{rows:AttendanceDto[];date:string;editable?:boolean;history?:boolean}){const statuses=useStatuses();if(!statuses.data)return <Loading/>;if(!rows.length)return <Empty>No agents match your filters.</Empty>;return <div className="attendance-table"><div className="table-heading"><span>AGENT</span><span>{history?'DATE':'TEAM LEADER'}</span><span>STATUS</span><span>UPDATED</span><span>{history?'DETAILS':'UPDATED BY'}</span></div>{rows.map(row=><AttendanceTableRow key={row.id} row={row} date={date} editable={editable} history={history} statuses={statuses.data!}/>)}</div>;}
function AttendanceTableRow({row,date,editable,history,statuses}:{row:AttendanceDto;date:string;editable:boolean;history:boolean;statuses:StatusDto[]}){const mutation=useMutation({mutationFn:(status:string)=>api('/attendance/'+row.agentId,json('PATCH',{status,date})),onSuccess:()=>{void queryClient.invalidateQueries({queryKey:['attendance']});void queryClient.invalidateQueries({queryKey:['dashboard']});}});return <div className="table-row"><div className="agent-identity"><Avatar name={row.agent.fullName} url={row.agent.avatarUrl}/><div><strong>{row.agent.fullName}</strong><small>{row.agent.jobTitle}</small></div></div><span className="table-leader">{history?row.attendanceDate.slice(0,10):row.agent.team?.teamLeader?.fullName??'Unassigned'}</span><div>{editable?<StatusSelector name={row.agent.fullName} statuses={statuses} statusKey={row.currentStatus} disabled={mutation.isPending} onSelect={status=>mutation.mutate(status)}/>:<StatusBadge statuses={statuses} statusKey={row.currentStatus}/>}</div><small>{timeLabel(row.lastUpdatedAt)}</small>{history?<Link className="text-link" to={`/admin/history/${row.agentId}?date=${row.attendanceDate.slice(0,10)}`}>View audit →</Link>:<small>{row.lastUpdatedBy?.fullName??'—'}</small>}{mutation.error&&<ErrorBox error={mutation.error}/>}</div>;}
