import {NavLink,Outlet,useNavigate,Link} from 'react-router-dom';
import {useEffect,useState} from 'react';
import {LayoutDashboard,ClipboardList,Users,UserRound,History,Settings,LogOut,Menu,CalendarCheck,ChevronRight} from 'lucide-react';
import {io} from 'socket.io-client';
import {api,json,queryClient,useAuth} from '../api';
import {Avatar,Brand,Modal} from './ui';
const adminLinks=[['dashboard','Dashboard',LayoutDashboard],['attendance','Attendance',ClipboardList],['teams','Teams',Users],['agents','Agents',UserRound],['history','History',History],['users','Users',Users],['settings','Settings',Settings]] as const;
export function Shell(){const {data}=useAuth(),user=data!.user,[menu,setMenu]=useState(false),navigate=useNavigate();const admin=user.role==='ADMIN';const [online,setOnline]=useState(navigator.onLine);const [logoutError,setLogoutError]=useState('');
 useEffect(()=>{const update=()=>setOnline(navigator.onLine);window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);};},[]);
 useEffect(()=>{if(!admin)return;const socket=io({withCredentials:true});const refresh=()=>{for(const key of ['attendance','dashboard','history','teams','agents','users'])void queryClient.invalidateQueries({queryKey:[key]});};socket.on('attendance:changed',refresh);socket.on('connect',refresh);return()=>{socket.disconnect();};},[admin]);
 async function logout(){try{await api('/auth/logout',json('POST',{}));queryClient.clear();navigate('/login',{replace:true});}catch{setLogoutError('Unable to sign out. Reconnect and try again.');}}
 const links=<nav className="side-links" aria-label="Admin navigation">{adminLinks.map(([path,label,Icon])=><NavLink key={path} to={'/admin/'+path} onClick={()=>setMenu(false)}><Icon size={19}/>{label}</NavLink>)}</nav>;
 return <div className={admin?'app-shell admin-shell':'app-shell leader-shell'}>{admin&&<aside className="sidebar"><Brand/><div className="nav-label">WORKSPACE</div>{links}<div className="sidebar-bottom"><span className="eyebrow">SEVEN CENTURY</span><p>People. Presence.<br/>Progress.</p><button onClick={logout}><LogOut size={17}/>Sign out</button></div></aside>}<div className="workspace"><header className="topbar">{admin?<div className="topbar-title"><button className="icon-button mobile-only" onClick={()=>setMenu(true)} aria-label="Open navigation"><Menu/></button><span>Team Management</span><ChevronRight size={15}/><b>Attendance</b></div>:<Brand/>}<Link className="profile-link" to="/profile"><span>{user.fullName}<small>{admin?'Administrator':'Team Leader'}</small></span><Avatar name={user.fullName} url={user.avatarUrl}/></Link></header>{!online&&<div className="offline-banner" role="status">You’re offline. Reconnect before updating attendance.</div>}{logoutError&&<div role="alert" className="error-message">{logoutError}</div>}<main className="content"><Outlet/></main>{!admin&&<nav className="bottom-nav" aria-label="Team navigation"><NavLink to="/today"><CalendarCheck size={21}/>Today</NavLink><NavLink to="/team"><Users size={21}/>My Team</NavLink><NavLink to="/profile"><UserRound size={21}/>Profile</NavLink></nav>}</div><Modal open={menu} onClose={()=>setMenu(false)} title="Navigation">{links}<button className="button" onClick={logout}>Sign out</button></Modal></div>;
}
