import * as Dialog from '@radix-ui/react-dialog';
import {X,Building2,Car,Users,Building,BadgeCheck,UserX,HeartPulse,Sun,Clock3,Check,ChevronDown} from 'lucide-react';
import {statusConfig,statusValues,type AttendanceStatus} from '../../../../packages/shared/src/index';
import type {ReactNode} from 'react';
const icons={Building2,Car,Users,Building,BadgeCheck,UserX,HeartPulse,Sun,Clock3};
export function Brand(){return <div className="brand"><svg viewBox="0 0 48 48" aria-hidden="true"><path d="M5 5h36L19 43H6l18-27H5z" fill="currentColor"/><path d="M32 30v13h11" fill="none" stroke="currentColor" strokeWidth="3"/></svg><div>SEVEN CENTURY<span>REAL ESTATE BROKERS LLC</span></div></div>;}
export function Avatar({name,url}:{name:string;url?:string|null}){return <span className="avatar">{url?<img src={url} alt="" referrerPolicy="no-referrer"/>:name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span>;}
export function StatusBadge({status}:{status:AttendanceStatus}){const config=statusConfig[status],Icon=icons[config.icon as keyof typeof icons];return <span className={`status ${config.color}`}><Icon size={15}/>{config.label}</span>;}
export function Modal({open,onClose,title,description,children}:{open:boolean;onClose:()=>void;title:string;description?:string;children:ReactNode}){return <Dialog.Root open={open} onOpenChange={v=>{if(!v)onClose();}}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className="modal"><div className="modal-heading"><div><Dialog.Title>{title}</Dialog.Title><Dialog.Description className={description?'muted':'sr-only'}>{description??title}</Dialog.Description></div><Dialog.Close className="icon-button" aria-label="Close"><X size={22}/></Dialog.Close></div>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;}
export function StatusSelector({status,onSelect,disabled,name}:{status:AttendanceStatus;onSelect:(value:AttendanceStatus)=>void;disabled?:boolean;name:string}){return <Dialog.Root><Dialog.Trigger disabled={disabled} className="status-trigger" aria-label={`Change status for ${name}`}><StatusBadge status={status}/><ChevronDown size={15}/></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className="modal status-sheet"><div className="modal-heading"><div><Dialog.Title>Select Status</Dialog.Title><Dialog.Description>{name}</Dialog.Description></div><Dialog.Close className="icon-button" aria-label="Close"><X/></Dialog.Close></div><div className="status-options">{statusValues.filter(v=>v!=='NOT_UPDATED').map(value=><Dialog.Close key={value} className="status-option" onClick={()=>onSelect(value)}><StatusBadge status={value}/>{status===value&&<Check size={18}/>}</Dialog.Close>)}</div></Dialog.Content></Dialog.Portal></Dialog.Root>;}
export function Progress({updated,total}:{updated:number;total:number}){const value=total?Math.round(updated/total*100):0;return <div className="progress" role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={100} aria-label="Attendance completion"><span style={{width:`${value}%`}}/></div>;}
export function Loading(){return <div className="skeletons" role="status" aria-label="Loading">{[1,2,3].map(i=><div className="skeleton" key={i}/>)}</div>;}
export function ErrorBox({error,retry}:{error:Error;retry?:()=>void}){return <div className="error-message" role="alert"><p>{error.message}</p>{retry&&<button className="text-link" onClick={retry}>Try again</button>}</div>;}
export function Empty({children}:{children:ReactNode}){return <div className="empty"><Users size={30}/><p>{children}</p></div>;}
export function PageHeader({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:ReactNode}){return <header className="page-header"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p className="muted">{description}</p>}</div>{actions&&<div className="header-actions">{actions}</div>}</header>;}
export function Pagination({page,total,pageSize,onChange}:{page:number;total:number;pageSize:number;onChange:(p:number)=>void}){return <div className="pagination"><span>{total} records · Page {page} of {Math.max(1,Math.ceil(total/pageSize))}</span><div><button className="button" disabled={page===1} onClick={()=>onChange(page-1)}>Previous</button><button className="button" disabled={page*pageSize>=total} onClick={()=>onChange(page+1)}>Next</button></div></div>;}
