import {Prisma,type PrismaClient} from '@prisma/client';
import type {FastifyInstance} from 'fastify';
import {z} from 'zod';
import {attendanceSchema,dubaiDate,filtersSchema,dashboardRangeSchema,summarize,isOverdue,type UserDto} from '../../../packages/shared/src/index.js';
import {authTools,userSelect} from './auth.js';
import type {Env} from './env.js';
import {ApiError} from './errors.js';
export const teamInclude={teamLeader:{select:userSelect}} as const;
export const attendanceInclude={agent:{include:{team:{include:teamInclude}}},team:{include:teamInclude},lastUpdatedBy:{select:{id:true,fullName:true}}} as const;
export function agentScope(user:Pick<UserDto,'id'|'role'>):Prisma.AgentWhereInput{return {active:true,...(user.role==='ADMIN'?{}:{team:{active:true,teamLeaderId:user.id}})};}
export async function serial<T>(db:PrismaClient,work:(tx:Prisma.TransactionClient)=>Promise<T>):Promise<T>{for(let attempt=0;;attempt++){try{return await db.$transaction(work,{isolationLevel:Prisma.TransactionIsolationLevel.Serializable,maxWait:10000,timeout:15000});}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2034'&&attempt<3)continue;throw error;}}}
export async function ensureToday(db:PrismaClient,user:UserDto,date:string){const agents=await db.agent.findMany({where:agentScope(user),select:{id:true,teamId:true,team:{select:{teamLeaderId:true}}}});if(agents.length)await db.dailyAttendance.createMany({data:agents.map(a=>({agentId:a.id,attendanceDate:new Date(date),teamId:a.teamId,leaderIdSnapshot:a.team?.teamLeaderId})),skipDuplicates:true});}
export async function updateAttendance(db:PrismaClient,user:UserDto,agentId:string,status:z.infer<typeof attendanceSchema>['status'],expectedDate?:string){return serial(db,async tx=>{const date=dubaiDate();if(expectedDate&&expectedDate!==date)throw new ApiError(409,'DATE_CHANGED','A new Dubai day has started. Refresh and try again.');const actor=await tx.user.findUnique({where:{id:user.id}});if(!actor?.active||actor.role!==user.role)throw new ApiError(403,'FORBIDDEN','Your account permissions have changed.');const agent=await tx.agent.findFirst({where:{id:agentId,...agentScope(user)},include:{team:true}});if(!agent)throw new ApiError(403,'FORBIDDEN','You cannot update this agent.');const row=await tx.dailyAttendance.upsert({where:{agentId_attendanceDate:{agentId,attendanceDate:new Date(date)}},create:{agentId,attendanceDate:new Date(date),teamId:agent.teamId,leaderIdSnapshot:agent.team?.teamLeaderId},update:{}});if(row.currentStatus===status)return row;const updated=await tx.dailyAttendance.update({where:{id:row.id},data:{currentStatus:status,lastUpdatedAt:new Date(),lastUpdatedById:user.id,teamId:agent.teamId,leaderIdSnapshot:agent.team?.teamLeaderId??null}});await tx.attendanceHistory.create({data:{agentId,attendanceDate:new Date(date),previousStatus:row.currentStatus,newStatus:status,changedById:user.id}});return updated;});}
export function activeStatuses(db:PrismaClient){return db.status.findMany({orderBy:{sortOrder:'asc'}});}
export async function attendanceRoutes(app:FastifyInstance,db:PrismaClient,env:Env,broadcast:()=>Promise<void>){const auth=authTools(db,env);
 app.get('/api/statuses',{preHandler:auth.requireAuth},async()=>activeStatuses(db));
 app.get('/api/me/team',{preHandler:auth.requireAuth},async req=>({teams:await db.team.findMany({where:req.user.role==='ADMIN'?{}:{teamLeaderId:req.user.id,active:true},include:{...teamInclude,agents:{where:{active:true},orderBy:{fullName:'asc'}}}})}));
 app.get('/api/me/team/attendance',{preHandler:auth.requireAuth},async req=>{const date=dubaiDate();await ensureToday(db,req.user,date);const rows=await db.dailyAttendance.findMany({where:{attendanceDate:new Date(date),agent:agentScope(req.user)},include:attendanceInclude,orderBy:{agent:{fullName:'asc'}}});return {date,rows,total:rows.length,page:1,pageSize:rows.length};});
 app.patch('/api/attendance/:agentId',{preHandler:auth.requireAuth},async req=>{const {agentId}=z.object({agentId:z.uuid()}).parse(req.params);const {status,date}=attendanceSchema.parse(req.body);const row=await updateAttendance(db,req.user,agentId,status,date);await broadcast();return row;});
 app.get('/api/admin/attendance',{preHandler:auth.requireAdmin},async req=>{const f=filtersSchema.parse(req.query);const date=f.date??dubaiDate(),today=date===dubaiDate();if(today)await ensureToday(db,req.user,date);const statusFilter=f.status?{equals:f.status}:f.role?{in:(await activeStatuses(db)).filter(s=>s.role===f.role).map(s=>s.key)}:undefined;const where:Prisma.DailyAttendanceWhereInput={attendanceDate:new Date(date),currentStatus:statusFilter,agent:{...(today?{active:true,teamId:f.teamId,team:f.leaderId?{teamLeaderId:f.leaderId}:undefined}:{}),fullName:f.search?{contains:f.search,mode:"insensitive"}:undefined},...(!today?{teamId:f.teamId,leaderIdSnapshot:f.leaderId}:{})};const [rows,total]=await db.$transaction([db.dailyAttendance.findMany({where,include:attendanceInclude,orderBy:{agent:{fullName:'asc'}},skip:(f.page-1)*f.pageSize,take:f.pageSize}),db.dailyAttendance.count({where})]);return {date,rows,total,page:f.page,pageSize:f.pageSize};});
 async function dashboard(user:UserDto,from?:string,to?:string){const today=dubaiDate();const rangeFrom=from??today,rangeTo=to??today,singleDay=rangeFrom===rangeTo;if(rangeTo===today)await ensureToday(db,user,today);const [rows,teams,settings,history,statuses]=await Promise.all([db.dailyAttendance.findMany({where:{attendanceDate:{gte:new Date(rangeFrom),lte:new Date(rangeTo)},agent:{active:true}},include:{agent:{select:{teamId:true}}}}),db.team.findMany({where:{active:true},include:teamInclude,orderBy:{name:'asc'}}),db.systemSettings.findUniqueOrThrow({where:{id:1}}),db.attendanceHistory.findMany({where:{attendanceDate:{gte:new Date(rangeFrom),lte:new Date(rangeTo)},agent:{active:true}},orderBy:{changedAt:'asc'}}),activeStatuses(db)]);const completion=teams.map(team=>{const members=rows.filter(r=>r.agent.teamId===team.id),s=summarize(members,statuses);const ids=new Set(members.map(r=>r.agentId));const changes=history.filter(h=>ids.has(h.agentId));if(!singleDay)return {team,...s,firstUpdate:changes[0]?.changedAt??null,latestUpdate:changes.at(-1)?.changedAt??null,completedAt:null,overdue:false};const state=new Map(members.map(r=>[r.agentId,'NOT_UPDATED']));let completedAt:Date|null=null;for(const change of changes){state.set(change.agentId,change.newStatus);if(members.length&&[...state.values()].every(v=>v!=='NOT_UPDATED'))completedAt??=change.changedAt;else completedAt=null;}return {team,...s,firstUpdate:changes[0]?.changedAt??null,latestUpdate:changes.at(-1)?.changedAt??null,completedAt,overdue:rangeTo===today&&s.updated<s.total&&isOverdue(settings.attendanceDeadline)};});return {date:rangeTo,from:rangeFrom,to:rangeTo,singleDay,summary:summarize(rows,statuses),completion,settings,statuses};}
 app.get('/api/admin/dashboard',{preHandler:auth.requireAdmin},async req=>{const f=dashboardRangeSchema.parse(req.query);return dashboard(req.user,f.from,f.to);});
 app.get('/api/admin/team-completion',{preHandler:auth.requireAdmin},async req=>{const f=dashboardRangeSchema.parse(req.query);return (await dashboard(req.user,f.from,f.to)).completion;});
}
