import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {useSearchParams} from 'react-router-dom';
import {Download} from 'lucide-react';
import {dubaiDate,csvCell,type AttendanceResult} from '../../../../packages/shared/src/index';
import {api,useStatuses} from '../api';
import {ErrorBox,Loading,PageHeader,Pagination} from '../components/ui';
import {AttendanceTable} from '../components/attendance';
import {Filters} from '../components/filters';
export default function Attendance(){const [params,setParams]=useSearchParams(),[exporting,setExporting]=useState(false),[exportError,setExportError]=useState<Error|null>(null);const query=useQuery({queryKey:['attendance','admin',params.toString()],queryFn:()=>api<AttendanceResult>('/admin/attendance?'+params.toString()),refetchInterval:30000});const statuses=useStatuses();async function download(){setExporting(true);setExportError(null);try{const labels=new Map((statuses.data??[]).map(s=>[s.key,s.label]));const p=new URLSearchParams(params);p.set('pageSize','100');let page=1;const lines=[['Agent','Date','Team','Status','Updated','Updated by'].map(csvCell).join(',')];for(;;page++){p.set('page',String(page));const result=await api<AttendanceResult>('/admin/attendance?'+p);lines.push(...result.rows.map(r=>[r.agent.fullName,r.attendanceDate.slice(0,10),r.team?.name??'',labels.get(r.currentStatus)??r.currentStatus,r.lastUpdatedAt??'',r.lastUpdatedBy?.fullName??''].map(csvCell).join(',')));if(page*100>=result.total)break;}const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='seven-century-attendance.csv';link.click();URL.revokeObjectURL(url);}catch(error){setExportError(error as Error);}finally{setExporting(false);}}return <><PageHeader eyebrow="COMPANY ATTENDANCE" title="Every agent. One view." description="Search, filter, and update your team’s current attendance." actions={<button className="button" disabled={exporting} onClick={download}><Download size={17}/>{exporting?'Exporting…':'Export CSV'}</button>}/><section className="panel"><Filters date={query.data?.date??dubaiDate()}/>{exportError&&<ErrorBox error={exportError}/>} {query.isPending?<Loading/>:query.error?<ErrorBox error={query.error} retry={()=>query.refetch()}/>:<><AttendanceTable rows={query.data.rows} date={query.data.date} editable={query.data.date===dubaiDate()}/><Pagination page={query.data.page} total={query.data.total} pageSize={query.data.pageSize} onChange={p=>setParams(prev=>{prev.set('page',String(p));return prev;})}/></>}</section></>;}
